export const catalogo = [
    {
      id: 1,
      titulo: "A culpa é das estrelas",
      descricao: "Inspirador, corajoso, irreverente e brutal, A culpa é das estrelas é a obra mais ambiciosa e emocionante de John Green, sobre a alegria e a tragédia que é viver e amar.",
      valor: 39.90,
      imagem: "A_culpa_é_das_estrelas.jpg",
      url: "https://www.amazon.com.br/Culpa-%C3%89-das-Estrelas/dp/8580572266",
      categoria: "Romance",
    },
    {
      id: 2,
      titulo: "A cinco passos de você",
      descricao: "Eles têm que ficar a cinco passos um do outro, mas, conforme a conexão entre os dois aumenta, a vontade de burlar a distância física parece insuportável. Um grande amor vale um passo roubado?",
      valor: 27.90,
      imagem: "A_cinco_passos_de_voce.jpg",
      url: "https://www.amazon.com.br/cinco-passos-voc%C3%AA-Rachael-Lippincott/dp/8525067423",
      categoria: "Romance",
    },
    {
      id: 3,
      titulo: "É Assim que Acaba",
      descricao: "Quando os dois se apaixonam, Lily se vê no meio de um relacionamento turbulento que não é o que ela esperava. Mas será que ela conseguirá enxergar isso, por mais doloroso que seja?",
      valor: 31.00,
      imagem: "É_assim_que_acaba.jpg",
      url: "https://www.amazon.com.br/Assim-que-Acaba-Colleen-Hoover/dp/8501112518",
      categoria: "Romance",
    },
    {
      id: 4,
      titulo: "O milagre da manhã",
      descricao: "É hora de acordar e conquistar todo o seu potencial. Você merece uma vida extraordinária!",
      valor: 42.80,
      imagem: "O_milagre_da_manha.jpg",
      url: "https://www.amazon.com.br/milagre-manh%C3%A3-Hal-Elrod/dp/8576849941",
      categoria: "Autoajuda",
    },
    {
      id: 5,
      titulo: "Textos cruéis demais para serem lidos rapidamente",
      descricao: "Para este livro, foram produzidos textos inéditos que ganharam a companhia das sensíveis ilustrações de Anália Moraes.",
      valor: 34.99,
      imagem: "Textos_crueis_demais_para_serem_lidos_rapidamente.jpg",
      url: "https://www.amazon.com.br/Textos-Cru%C3%A9is-Demais-Serem-Rapidamente/dp/8525065366",
      categoria: "Autoajuda",
    },
    {
      id: 6,
      titulo: "A Ruína de um Reino",
      descricao: "Uma releitura sombria de A Pequena Sereia, best-seller internacional e sensação no TikTok",
      valor: 52.59,
      imagem: "A_ruina_de_um_reino.jpg",
      url: "https://www.amazon.com.br/Ru%C3%ADna-um-Reino-Alexandra-Christo/dp/6599166156",
      categoria: "fantasia",
    },
    {
      id: 7,
      titulo: "A rainha vermelha",
      descricao: "O mundo de Mare Barrow é dividido pelo sangue: vermelho ou prateado. Mare e sua família são vermelhos: plebeus, humildes, destinados a servir uma elite prateada cujos poderes sobrenaturais os tornam quase deuses.",
      valor: 35.00,
      imagem: "A_rainha_vermelha.jpg",
      url: "https://www.amazon.com.br/rainha-vermelha-Victoria-Aveyard/dp/8565765695",
      categoria: "fantasia",
    },
    {
      id: 8,
      titulo: "O Homem de Giz",
      descricao: "Alternando habilidosamente entre presente e passado, O Homem de Giz traz o melhor do suspense: personagens maravilhosamente construídos, mistérios de prender o fôlego e reviravoltas que vão impressionar até os leitores mais escaldados.",
      valor: 42.90,
      imagem: "O_homem_de_giz.jpg",
      url: "https://www.amazon.com.br/Homem-Giz-C-J-Tudor/dp/8551002937",
      categoria: "fantasia",
    },
];